version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Wiki"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qw7sqsnil282"
s3_prefix = "Wiki"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=184705484488.dkr.ecr.us-east-1.amazonaws.com/wikibf111e36/helloworldfunction19d43fc4repo"]
